// frontend/src/pages/Community/PostDetail.tsx
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import {
  Avatar,
  Button,
  Card,
  Divider,
  Empty,
  Form,
  Input,
  List,
  Modal,
  Select,
  Space,
  Spin,
  Switch,
  Tag,
  Typography,
  message,
} from 'antd'
import {
  ArrowLeftOutlined,
  EyeOutlined,
  LikeFilled,
  LikeOutlined,
  MessageOutlined,
  UserOutlined,
} from '@ant-design/icons'
import { communityApi, CommunityComment, CommunityPost } from '@/api/community'
import { categoryApi, type Category } from '@/api/modules'
import { useAppStore } from '@/stores/appStore'

const { Paragraph, Text, Title } = Typography
const { TextArea } = Input

const getUserIdFromToken = () => {
  const token = localStorage.getItem('token')
  if (!token) return ''

  try {
    const payload = JSON.parse(window.atob(token.split('.')[1] || ''))
    return payload?.userId ? String(payload.userId) : ''
  } catch {
    return ''
  }
}

export function PostDetail() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const user = useAppStore((state) => state.user)
  const [post, setPost] = useState<CommunityPost | null>(null)
  const [comments, setComments] = useState<CommunityComment[]>([])
  const [categories, setCategories] = useState<Array<Pick<Category, 'id' | 'name'>>>([])
  const [loading, setLoading] = useState(true)
  const [commentsLoading, setCommentsLoading] = useState(false)
  const [commentContent, setCommentContent] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [editSubmitting, setEditSubmitting] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [replyTarget, setReplyTarget] = useState<{ parentId: number; replyToId: number; authorName: string } | null>(null)
  const [commentPagination, setCommentPagination] = useState({
    page: 1,
    pageSize: 10,
    total: 0,
    totalPages: 0,
  })
  const [form] = Form.useForm()

  const currentUserId = user?.id ? String(user.id) : getUserIdFromToken()
  const postCategoryOptions = [
    { label: '不分类', value: '' },
    ...categories.map((item) => ({ label: item.name, value: String(item.id) })),
  ]
  const canManagePost = !!post && !!currentUserId && String(post.authorId) === currentUserId

  useEffect(() => {
    fetchCategories()
  }, [])

  useEffect(() => {
    if (id) {
      fetchPost(Number(id))
      fetchComments(Number(id), 1)
    }
  }, [id])

  const fetchCategories = async () => {
    try {
      const result = await categoryApi.getAll()
      setCategories((result || []).map((item) => ({ id: item.id, name: item.name })))
    } catch (_error) {
      setCategories([])
    }
  }

  const fetchPost = async (postId: number) => {
    setLoading(true)
    try {
      const data = (await communityApi.getPostById(postId)) as CommunityPost
      setPost(data)
    } catch (_error) {
      message.error('获取帖子失败')
    } finally {
      setLoading(false)
    }
  }

  const fetchComments = async (postId: number, page = commentPagination.page) => {
    setCommentsLoading(true)
    try {
      const result = await communityApi.getComments(postId, {
        page,
        pageSize: commentPagination.pageSize,
      })
      const data = result as unknown as {
        list: CommunityComment[]
        pagination?: { page: number; pageSize: number; total: number; totalPages: number }
      }
      setComments(data.list || [])
      setCommentPagination((prev) => ({
        ...prev,
        page: data.pagination?.page ?? page,
        pageSize: data.pagination?.pageSize ?? prev.pageSize,
        total: data.pagination?.total ?? 0,
        totalPages: data.pagination?.totalPages ?? 0,
      }))
    } catch (_error) {
      console.error('获取评论失败:', _error)
    } finally {
      setCommentsLoading(false)
    }
  }

  const ensureLogin = () => {
    const token = localStorage.getItem('token')
    if (!token) {
      message.warning('请先登录')
      navigate('/login')
      return false
    }
    return true
  }

  const handleLike = async () => {
    if (!post) return
    if (!ensureLogin()) return

    try {
      if (post.isLiked) {
        await communityApi.unlikePost(post.id)
      } else {
        await communityApi.likePost(post.id)
      }
      setPost({
        ...post,
        isLiked: !post.isLiked,
        likeCount: post.likeCount + (post.isLiked ? -1 : 1),
      })
    } catch (_error) {
      message.error('操作失败')
    }
  }

  const handleOpenEdit = () => {
    if (!post || !canManagePost) return

    form.setFieldsValue({
      title: post.title,
      content: post.content,
      categoryId: post.categoryId || '',
      isAnonymous: post.isAnonymous,
    })
    setShowEditModal(true)
  }

  const handleCloseEdit = () => {
    setShowEditModal(false)
    form.resetFields()
  }

  const handleSubmitEdit = async (values: {
    title: string
    content: string
    categoryId?: string
    isAnonymous?: boolean
  }) => {
    if (!post) return

    setEditSubmitting(true)
    try {
      const updatedPost = (await communityApi.updatePost(post.id, {
        title: values.title.trim(),
        content: values.content.trim(),
        categoryId: values.categoryId || undefined,
        isAnonymous: Boolean(values.isAnonymous),
      })) as CommunityPost
      setPost(updatedPost)
      handleCloseEdit()
      message.success('帖子已更新')
    } catch (_error) {
      message.error('更新失败')
    } finally {
      setEditSubmitting(false)
    }
  }

  const handleDeletePost = () => {
    if (!post || !canManagePost) return

    Modal.confirm({
      title: '删除帖子',
      content: '删除后不可恢复，确认继续吗？',
      okText: '删除',
      cancelText: '取消',
      okButtonProps: { danger: true },
      onOk: async () => {
        try {
          await communityApi.deletePost(post.id)
          message.success('删除成功')
          navigate('/community')
        } catch (_error) {
          message.error('删除失败')
        }
      },
    })
  }

  const handleDeleteComment = (commentId: number) => {
    if (!post) return

    Modal.confirm({
      title: '删除评论',
      content: '删除后不可恢复，确认继续吗？',
      okText: '删除',
      cancelText: '取消',
      okButtonProps: { danger: true },
      onOk: async () => {
        try {
          const result = await communityApi.deleteComment(commentId)
          setPost((prev) =>
            prev
              ? { ...prev, commentCount: Math.max(0, prev.commentCount - (result.deletedCount || 0)) }
              : prev
          )
          if (id) {
            const nextPage = comments.length === 1 && commentPagination.page > 1
              ? commentPagination.page - 1
              : commentPagination.page
            fetchComments(Number(id), nextPage)
          }
          message.success('删除成功')
        } catch (_error) {
          message.error('删除失败')
        }
      },
    })
  }

  const canDeleteComment = (authorId: string) => !!currentUserId && String(authorId) === currentUserId

  const handleSubmitComment = async () => {
    if (!commentContent.trim() || !id) return
    if (!ensureLogin()) return

    setSubmitting(true)
    try {
      await communityApi.createComment(Number(id), {
        content: commentContent.trim(),
        parentId: replyTarget?.parentId,
        replyToId: replyTarget?.replyToId,
      })

      setCommentContent('')
      setReplyTarget(null)
      setPost((prev) => (prev ? { ...prev, commentCount: prev.commentCount + 1 } : prev))
      await fetchComments(Number(id), 1)
      message.success('评论成功')
    } catch (_error) {
      message.error('评论失败')
    } finally {
      setSubmitting(false)
    }
  }

  if (loading) {
    return (
      <div style={{ textAlign: 'center', padding: 100 }}>
        <Spin size="large" />
      </div>
    )
  }

  if (!post) {
    return (
      <Card>
        <div style={{ textAlign: 'center', padding: 50 }}>
          <Title level={4}>帖子不存在或已删除</Title>
          <Button type="primary" onClick={() => navigate('/community')}>
            返回社区
          </Button>
        </div>
      </Card>
    )
  }

  return (
    <div>
      <Button
        type="text"
        icon={<ArrowLeftOutlined />}
        onClick={() => navigate('/community')}
        style={{ marginBottom: 16 }}
      >
        返回社区
      </Button>

      <Card>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16, marginBottom: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center' }}>
            <Avatar icon={<UserOutlined />} src={post.author?.avatar} />
            <div style={{ marginLeft: 12 }}>
              <Text strong>
                {post.isAnonymous ? '匿名用户' : post.author?.nickname || post.author?.username}
              </Text>
              <br />
              <Text type="secondary" style={{ fontSize: 12 }}>
                {new Date(post.createdAt).toLocaleString()}
              </Text>
            </div>
          </div>
          {canManagePost && (
            <Space size={4}>
              <Button type="link" size="small" onClick={handleOpenEdit}>
                编辑
              </Button>
              <Button type="link" size="small" danger onClick={handleDeletePost}>
                删除
              </Button>
            </Space>
          )}
        </div>

        <Title level={3}>
          {post.isPinned && <Tag color="red">置顶</Tag>}
          {post.title}
        </Title>

        <Paragraph style={{ whiteSpace: 'pre-wrap', lineHeight: 1.8, fontSize: 15 }}>
          {post.content}
        </Paragraph>

        <Space wrap style={{ marginBottom: 16 }}>
          {(post.categoryName || post.category) && (
            <Tag>{post.categoryName || post.category}</Tag>
          )}
          {post.isAnonymous && <Tag color="gold">匿名</Tag>}
        </Space>

        <Divider />

        <Space size="large">
          <Button
            type={post.isLiked ? 'primary' : 'default'}
            icon={post.isLiked ? <LikeFilled /> : <LikeOutlined />}
            onClick={handleLike}
          >
            {post.likeCount}
          </Button>
          <span>
            <MessageOutlined /> {post.commentCount} 评论
          </span>
          <span>
            <EyeOutlined /> {post.viewCount} 浏览
          </span>
        </Space>
      </Card>

      <Card title={`评论 (${post.commentCount})`} style={{ marginTop: 16 }}>
        <div style={{ marginBottom: 24 }}>
          {replyTarget && (
            <div style={{ marginBottom: 8, display: 'flex', justifyContent: 'space-between', gap: 12 }}>
              <Text type="secondary">正在回复：{replyTarget.authorName}</Text>
              <Button type="link" size="small" onClick={() => setReplyTarget(null)}>
                取消
              </Button>
            </div>
          )}
          <TextArea
            rows={3}
            value={commentContent}
            onChange={(event) => setCommentContent(event.target.value)}
            placeholder={replyTarget ? `回复 ${replyTarget.authorName}...` : '写下你的评论...'}
            maxLength={1000}
          />
          <Button
            type="primary"
            style={{ marginTop: 8 }}
            onClick={handleSubmitComment}
            loading={submitting}
            disabled={!commentContent.trim()}
          >
            发表评论
          </Button>
        </div>

        <Spin spinning={commentsLoading}>
          {comments.length > 0 ? (
            <List
              dataSource={comments}
              renderItem={(comment) => (
                <List.Item>
                  <div style={{ width: '100%' }}>
                    <List.Item.Meta
                      avatar={<Avatar icon={<UserOutlined />} src={comment.author?.avatar} />}
                      title={
                        <Space>
                          <Text strong>
                            {comment.author?.nickname || comment.author?.username || '用户'}
                          </Text>
                          <Text type="secondary" style={{ fontSize: 12 }}>
                            {new Date(comment.createdAt).toLocaleString()}
                          </Text>
                          {canDeleteComment(comment.authorId) && (
                            <Button
                              type="link"
                              size="small"
                              danger
                              onClick={() => handleDeleteComment(comment.id)}
                            >
                              删除
                            </Button>
                          )}
                        </Space>
                      }
                      description={
                        <>
                          <div>{comment.content}</div>
                          <div style={{ marginTop: 8 }}>
                            <Button
                              type="link"
                              size="small"
                              style={{ paddingLeft: 0 }}
                              onClick={() => setReplyTarget({
                                parentId: comment.id,
                                replyToId: comment.id,
                                authorName: comment.author?.nickname || comment.author?.username || '用户',
                              })}
                            >
                              回复
                            </Button>
                          </div>
                        </>
                      }
                    />

                    {!!comment.replies?.length && (
                      <div style={{ marginLeft: 52, marginTop: 8, padding: 12, background: '#f7f9fc', borderRadius: 12 }}>
                        {comment.replies.map((reply) => (
                          <div key={reply.id} style={{ marginBottom: 12 }}>
                            <Space size={8} wrap>
                              <Text strong>{reply.author?.nickname || reply.author?.username || '用户'}</Text>
                              <Text type="secondary" style={{ fontSize: 12 }}>
                                {new Date(reply.createdAt).toLocaleString()}
                              </Text>
                              {canDeleteComment(reply.authorId) && (
                                <Button
                                  type="link"
                                  size="small"
                                  danger
                                  onClick={() => handleDeleteComment(reply.id)}
                                >
                                  删除
                                </Button>
                              )}
                            </Space>
                            <Paragraph style={{ margin: '6px 0 0', whiteSpace: 'pre-wrap' }}>{reply.content}</Paragraph>
                            <Button
                              type="link"
                              size="small"
                              style={{ paddingLeft: 0 }}
                              onClick={() => setReplyTarget({
                                parentId: comment.id,
                                replyToId: reply.id,
                                authorName: reply.author?.nickname || reply.author?.username || '用户',
                              })}
                            >
                              回复
                            </Button>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </List.Item>
              )}
              pagination={{
                current: commentPagination.page,
                total: commentPagination.total,
                pageSize: commentPagination.pageSize,
                onChange: (page) => {
                  if (!id) return
                  fetchComments(Number(id), page)
                },
                showTotal: (total) => `共 ${total} 条`,
              }}
            />
          ) : (
            <Empty description="暂无评论，来说点什么吧" />
          )}
        </Spin>
      </Card>

      <Modal
        title="编辑帖子"
        open={showEditModal}
        onCancel={handleCloseEdit}
        footer={null}
        destroyOnClose
      >
        <Form
          form={form}
          layout="vertical"
          onFinish={handleSubmitEdit}
          initialValues={{ isAnonymous: false, categoryId: '' }}
        >
          <Form.Item name="title" label="标题" rules={[{ required: true, message: '请输入标题' }]}>
            <Input placeholder="请输入帖子标题" maxLength={100} />
          </Form.Item>
          <Form.Item name="categoryId" label="分类">
            <Select options={postCategoryOptions} />
          </Form.Item>
          <Form.Item name="content" label="内容" rules={[{ required: true, message: '请输入内容' }]}>
            <Input.TextArea rows={6} placeholder="分享您的经验..." maxLength={5000} showCount />
          </Form.Item>
          <Form.Item name="isAnonymous" label="匿名发布" valuePropName="checked">
            <Switch />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" block loading={editSubmitting}>
              保存修改
            </Button>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

// mini-program/src/pages/post-detail/index.vue
<template>
  <view class="detail-page">
    <!-- Loading -->
    <view v-if="loading" class="loading-box">
      <text class="loading-text">加载中...</text>
    </view>

    <view v-else-if="!post" class="empty-box">
      <text class="empty-text">帖子不存在</text>
    </view>

    <view v-else class="detail-content">
      <!-- Post Card -->
      <view class="post-card">
        <!-- Author Row -->
        <view class="post-author-row">
          <view class="avatar avatar-fallback">
            <text class="avatar-text">{{ post.isAnonymous ? '匿' : ((post.author?.nickname || post.author?.username || '用')[0]) }}</text>
          </view>
          <view class="author-info">
            <text class="author-name">
              {{ post.isAnonymous ? '匿名用户' : (post.author?.nickname || post.author?.username || '用户') }}
            </text>
            <text class="post-date">{{ formatDate(post.createdAt) }}</text>
          </view>
        </view>

        <!-- Title -->
        <view class="post-title-row">
          <view v-if="post.isPinned" class="pin-tag">
            <text class="pin-tag-text">置顶</text>
          </view>
          <text class="post-title">{{ post.title }}</text>
        </view>

        <!-- Full Content -->
        <text class="post-body">{{ post.content }}</text>

        <!-- Category Tag -->
        <view v-if="post.categoryName || post.category" class="category-tag">
          <text class="category-tag-text">{{ getCategoryLabel(post.categoryName || post.category || '') }}</text>
        </view>

        <!-- Stats Row -->
        <view class="stats-row">
          <view class="stat-item" @tap="onToggleLike">
            <text class="stat-icon" :class="{ 'stat-icon--liked': post.isLiked }">♥</text>
            <text class="stat-num">{{ post.likeCount || 0 }}</text>
          </view>
          <view class="stat-item">
            <text class="stat-icon">💬</text>
            <text class="stat-num">{{ post.commentCount || 0 }}</text>
          </view>
          <view class="stat-item">
            <text class="stat-icon">👁</text>
            <text class="stat-num">{{ post.viewCount || 0 }}</text>
          </view>
        </view>

        <view v-if="canManagePost" class="post-actions">
          <view class="post-action-btn post-action-btn--edit" @tap="openEditPost">
            <text class="post-action-text post-action-text--edit">编辑帖子</text>
          </view>
          <view class="post-action-btn" @tap="handleDeletePost">
            <text class="post-action-text">删除帖子</text>
          </view>
        </view>
      </view>

      <!-- Divider -->
      <view class="divider" />

      <!-- Comments Section -->
      <view class="comment-section">
        <text class="section-title">评论 ({{ post?.commentCount || 0 }})</text>

        <!-- Comment Input -->
        <view class="comment-input-box">
          <view v-if="replyTarget" class="reply-target-bar">
            <text class="reply-target-text">正在回复：{{ replyTarget.authorName }}</text>
            <text class="reply-target-cancel" @tap="clearReplyTarget">取消</text>
          </view>
          <textarea
            v-model="commentText"
            class="comment-textarea"
            :placeholder="replyTarget ? `回复 ${replyTarget.authorName}...` : '写下你的评论...'"
            :auto-height="true"
            :maxlength="500"
          />
          <view class="comment-submit-btn" @tap="submitComment">
            <text class="comment-submit-text">发表评论</text>
          </view>
        </view>

        <!-- Comment List -->
        <view v-if="commentsLoading" class="loading-box">
          <text class="loading-text">加载评论中...</text>
        </view>

        <view v-else-if="comments.length === 0" class="empty-comments">
          <text class="empty-text">暂无评论，快来发表第一条评论吧</text>
        </view>

        <view v-else class="comment-list">
          <view v-for="comment in comments" :key="comment.id" class="comment-card">
            <view class="comment-header">
              <view class="comment-avatar comment-avatar-fallback">
                <text class="comment-avatar-text">{{ (comment.author?.nickname || comment.author?.username || '用')[0] }}</text>
              </view>
              <view class="comment-author-info">
                <text class="comment-author-name">
                  {{ comment.author?.nickname || comment.author?.username || '用户' }}
                </text>
                <text class="comment-date">{{ formatDate(comment.createdAt) }}</text>
              </view>
              <view v-if="canDeleteComment(comment.authorId)" class="comment-delete-btn" @tap="handleDeleteComment(comment.id)">
                <text class="comment-delete-text">删除</text>
              </view>
            </view>
            <text class="comment-content">{{ comment.content }}</text>
            <view class="comment-actions">
              <text class="comment-action-link" @tap="setReplyTarget(comment.id, comment.id, comment.author?.nickname || comment.author?.username || '用户')">回复</text>
            </view>
            <view v-if="comment.replies?.length" class="reply-list">
              <view v-for="reply in comment.replies" :key="reply.id" class="reply-card">
                <view class="reply-head">
                  <text class="reply-author">{{ reply.author?.nickname || reply.author?.username || '用户' }}</text>
                  <text class="reply-date">{{ formatDate(reply.createdAt) }}</text>
                </view>
                <text class="reply-content">{{ reply.content }}</text>
                <view class="reply-actions">
                  <text class="comment-action-link" @tap="setReplyTarget(comment.id, reply.id, reply.author?.nickname || reply.author?.username || '用户')">回复</text>
                  <text v-if="canDeleteComment(reply.authorId)" class="comment-delete-text" @tap="handleDeleteComment(reply.id)">删除</text>
                </view>
              </view>
            </view>
          </view>
        </view>

        <!-- Comment Pagination -->
        <view v-if="commentPagination.totalPages > 1" class="pagination">
          <view
            class="page-btn"
            :class="{ 'page-btn--disabled': commentPagination.page <= 1 }"
            @tap="changeCommentPage(commentPagination.page - 1)"
          >
            <text class="page-btn-text">上一页</text>
          </view>
          <text class="page-info">{{ commentPagination.page }} / {{ commentPagination.totalPages }}</text>
          <view
            class="page-btn"
            :class="{ 'page-btn--disabled': commentPagination.page >= commentPagination.totalPages }"
            @tap="changeCommentPage(commentPagination.page + 1)"
          >
            <text class="page-btn-text">下一页</text>
          </view>
        </view>
      </view>
    </view>

    <view v-if="showEditModal" class="modal-mask" @tap.self="closeEditModal">
      <view class="modal-content">
        <text class="modal-title">编辑帖子</text>

        <view class="form-item">
          <text class="form-label">标题</text>
          <input
            v-model="postForm.title"
            class="form-input"
            placeholder="请输入标题"
          />
        </view>

        <view class="form-item">
          <text class="form-label">分类</text>
          <picker :range="categoryOptions" range-key="name" :value="selectedCategoryIndex" @change="onCategoryChange">
            <view class="form-picker">
              <text :class="postForm.categoryId ? 'form-picker-text' : 'placeholder-text'">
                {{ selectedCategoryLabel }}
              </text>
            </view>
          </picker>
        </view>

        <view class="form-item">
          <text class="form-label">内容</text>
          <textarea
            v-model="postForm.content"
            class="form-textarea"
            placeholder="分享你的经验和想法..."
          />
        </view>

        <view class="form-item form-item--switch">
          <text class="form-label">匿名发布</text>
          <switch :checked="postForm.isAnonymous" color="#2ea97d" @change="onAnonymousChange" />
        </view>

        <view class="modal-actions">
          <view class="modal-btn modal-btn--cancel" @tap="closeEditModal">
            <text class="modal-btn-text">取消</text>
          </view>
          <view class="modal-btn modal-btn--confirm" @tap="submitPostUpdate">
            <text class="modal-btn-text modal-btn-text--white">保存修改</text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed, ref, reactive } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { communityApi } from '@/api/community'
import type { CommunityPost, CommunityComment } from '@/api/community'
import { categoryApi, type Category } from '@/api/modules'
import dayjs from 'dayjs'

const postId = ref(0)
const loading = ref(false)
const post = ref<CommunityPost | null>(null)
const comments = ref<CommunityComment[]>([])
const categories = ref<Array<Pick<Category, 'id' | 'name'>>>([])
const commentsLoading = ref(false)
const commentText = ref('')
const commentPagination = reactive({ page: 1, pageSize: 20, total: 0, totalPages: 0 })
const currentUserId = ref('')
const showEditModal = ref(false)
const postForm = reactive({ title: '', content: '', categoryId: '', isAnonymous: false })
const replyTarget = ref<{ parentId: number; replyToId: number; authorName: string } | null>(null)

const formatDate = (date: string) => dayjs(date).format('YYYY-MM-DD HH:mm')
const canManagePost = computed(() => !!post.value && post.value.authorId === currentUserId.value)
const categoryOptions = computed(() => [{ id: '', name: '不分类' }, ...categories.value])
const selectedCategoryIndex = computed(() => {
  const index = categoryOptions.value.findIndex((item) => String(item.id) === postForm.categoryId)
  return index >= 0 ? index : 0
})
const selectedCategoryLabel = computed(() => {
  return categoryOptions.value[selectedCategoryIndex.value]?.name || '不分类'
})

const ensureLogin = () => {
  const token = uni.getStorageSync('token')
  if (!token) {
    uni.navigateTo({ url: '/pages/login/index' })
    return false
  }
  return true
}

const getCategoryLabel = (value: string) => {
  const category = categories.value.find((item) => String(item.id) === value || item.name === value)
  return category?.name || value
}

const fetchCategories = async () => {
  try {
    const res = await categoryApi.getAll()
    categories.value = (res || []).map((item) => ({ id: item.id, name: item.name }))
  } catch (_err) {
    categories.value = []
  }
}

const fetchPost = async () => {
  loading.value = true
  try {
    const res = await communityApi.getPostById(postId.value) as any
    post.value = res
  } catch (_err) {
    uni.showToast({ title: '加载失败', icon: 'none' })
  } finally {
    loading.value = false
  }
}

const fetchComments = async () => {
  commentsLoading.value = true
  try {
    const res = await communityApi.getComments(postId.value, {
      page: commentPagination.page,
      pageSize: commentPagination.pageSize,
    }) as any
    comments.value = res.list || []
    if (res.pagination) {
      commentPagination.total = res.pagination.total
      commentPagination.totalPages = res.pagination.totalPages
    }
  } catch (_err) {
    console.error('加载评论失败')
  } finally {
    commentsLoading.value = false
  }
}

const changeCommentPage = (page: number) => {
  if (page < 1 || page > commentPagination.totalPages) return
  commentPagination.page = page
  fetchComments()
}

const onToggleLike = async () => {
  if (!post.value) return
  if (!ensureLogin()) return
  try {
    if (post.value.isLiked) {
      await communityApi.unlikePost(post.value.id)
      post.value.isLiked = false
      post.value.likeCount--
    } else {
      await communityApi.likePost(post.value.id)
      post.value.isLiked = true
      post.value.likeCount++
    }
  } catch (_err) {
    uni.showToast({ title: '操作失败', icon: 'none' })
  }
}

const canDeleteComment = (authorId: string) => {
  return authorId === currentUserId.value
}

const setReplyTarget = (parentId: number, replyToId: number, authorName: string) => {
  replyTarget.value = { parentId, replyToId, authorName }
}

const clearReplyTarget = () => {
  replyTarget.value = null
}

const openEditPost = () => {
  if (!post.value || !canManagePost.value) return
  postForm.title = post.value.title
  postForm.content = post.value.content
  postForm.categoryId = post.value.categoryId || ''
  postForm.isAnonymous = Boolean(post.value.isAnonymous)
  showEditModal.value = true
}

const closeEditModal = () => {
  showEditModal.value = false
}

const onCategoryChange = (e: { detail: { value: number | string } }) => {
  const target = categoryOptions.value[Number(e.detail.value)]
  postForm.categoryId = target ? String(target.id || '') : ''
}

const onAnonymousChange = (e: any) => {
  postForm.isAnonymous = Boolean(e?.detail?.value)
}

const submitPostUpdate = async () => {
  if (!post.value) return
  if (!postForm.title.trim()) {
    uni.showToast({ title: '请输入标题', icon: 'none' })
    return
  }
  if (!postForm.content.trim()) {
    uni.showToast({ title: '请输入内容', icon: 'none' })
    return
  }

  try {
    const updatedPost = await communityApi.updatePost(post.value.id, {
      title: postForm.title.trim(),
      content: postForm.content.trim(),
      categoryId: postForm.categoryId || undefined,
      isAnonymous: postForm.isAnonymous,
    })
    post.value = updatedPost as CommunityPost
    closeEditModal()
    uni.showToast({ title: '更新成功', icon: 'success' })
  } catch (_err) {
    uni.showToast({ title: '更新失败', icon: 'none' })
  }
}

const handleDeletePost = () => {
  if (!post.value || !canManagePost.value) return
  uni.showModal({
    title: '删除帖子',
    content: '删除后将无法恢复，确认继续吗？',
    success: async (res) => {
      if (!res.confirm || !post.value) return
      try {
        await communityApi.deletePost(post.value.id)
        uni.showToast({ title: '删除成功', icon: 'success' })
        setTimeout(() => {
          uni.navigateBack()
        }, 500)
      } catch (_err) {
        uni.showToast({ title: '删除失败', icon: 'none' })
      }
    },
  })
}

const handleDeleteComment = (id: number) => {
  uni.showModal({
    title: '删除评论',
    content: '确认删除这条评论吗？',
    success: async (res) => {
      if (!res.confirm) return
      try {
        const result = await communityApi.deleteComment(id) as { deletedCount?: number }
        if (post.value && result.deletedCount) {
          post.value.commentCount = Math.max(0, post.value.commentCount - result.deletedCount)
        }
        fetchComments()
        uni.showToast({ title: '删除成功', icon: 'success' })
      } catch (_err) {
        uni.showToast({ title: '删除失败', icon: 'none' })
      }
    },
  })
}

const submitComment = async () => {
  if (!ensureLogin()) return
  if (!commentText.value.trim()) {
    uni.showToast({ title: '请输入评论内容', icon: 'none' })
    return
  }
  try {
    await communityApi.createComment(postId.value, {
      content: commentText.value.trim(),
      parentId: replyTarget.value ? replyTarget.value.parentId : undefined,
      replyToId: replyTarget.value ? replyTarget.value.replyToId : undefined,
    })
    commentText.value = ''
    clearReplyTarget()
    uni.showToast({ title: '评论成功', icon: 'success' })
    // Refresh comments
    commentPagination.page = 1
    fetchComments()
    // Update comment count
    if (post.value) {
      post.value.commentCount++
    }
  } catch (_err) {
    uni.showToast({ title: '评论失败', icon: 'none' })
  }
}

onLoad((options) => {
  const storedUser = uni.getStorageSync('user') as { id?: string } | undefined
  currentUserId.value = storedUser?.id ? String(storedUser.id) : ''
  fetchCategories()
  if (options?.id) {
    postId.value = Number(options.id)
    fetchPost()
    fetchComments()
  }
})
</script>

<style scoped>
.detail-page {
  min-height: 100vh;
  background-color: #f5f5f5;
  padding-bottom: 40rpx;
}

.loading-box,
.empty-box {
  display: flex;
  justify-content: center;
  padding: 100rpx 0;
}

.loading-text,
.empty-text {
  font-size: 28rpx;
  color: #999999;
}

.detail-content {
  padding: 0;
}

.post-card {
  background-color: #ffffff;
  padding: 32rpx;
  margin-bottom: 0;
}

.post-author-row {
  display: flex;
  align-items: center;
  margin-bottom: 24rpx;
}

.avatar {
  width: 80rpx;
  height: 80rpx;
  border-radius: 50%;
  margin-right: 20rpx;
  background-color: #eeeeee;
}

.avatar-fallback {
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba(24, 144, 255, 0.15);
}

.avatar-text {
  font-size: 30rpx;
  font-weight: bold;
  color: #1890ff;
}

.author-info {
  display: flex;
  flex-direction: column;
}

.author-name {
  font-size: 28rpx;
  color: #333333;
  font-weight: 500;
}

.post-date {
  font-size: 24rpx;
  color: #999999;
  margin-top: 4rpx;
}

.post-title-row {
  display: flex;
  align-items: center;
  gap: 10rpx;
  margin-bottom: 20rpx;
}

.pin-tag {
  background-color: #ff4d4f;
  border-radius: 6rpx;
  padding: 2rpx 10rpx;
  flex-shrink: 0;
}

.pin-tag-text {
  font-size: 20rpx;
  color: #ffffff;
}

.post-title {
  font-size: 34rpx;
  font-weight: bold;
  color: #333333;
}

.post-body {
  font-size: 28rpx;
  color: #444444;
  line-height: 1.8;
  margin-bottom: 24rpx;
}

.category-tag {
  display: inline-flex;
  background-color: #e6f7ff;
  border-radius: 6rpx;
  padding: 4rpx 14rpx;
  margin-bottom: 20rpx;
}

.category-tag-text {
  font-size: 22rpx;
  color: #1890ff;
}

.stats-row {
  display: flex;
  gap: 32rpx;
  padding-top: 20rpx;
  border-top: 1rpx solid #f0f0f0;
}

.post-actions {
  margin-top: 24rpx;
  display: flex;
  justify-content: flex-end;
  gap: 16rpx;
}

.post-action-btn {
  padding: 10rpx 20rpx;
  border-radius: 999rpx;
  background-color: rgba(255, 77, 79, 0.08);
}

.post-action-btn--edit {
  background-color: rgba(24, 144, 255, 0.08);
}

.post-action-text {
  font-size: 24rpx;
  color: #d84b4b;
  font-weight: 600;
}

.post-action-text--edit {
  color: #1890ff;
}

.stat-item {
  display: flex;
  align-items: center;
  gap: 8rpx;
}

.stat-icon {
  font-size: 28rpx;
}

.stat-icon--liked {
  color: #ff4d4f;
}

.stat-num {
  font-size: 26rpx;
  color: #999999;
}

.divider {
  height: 16rpx;
  background-color: #f5f5f5;
}

.comment-section {
  background-color: #ffffff;
  padding: 32rpx;
}

.section-title {
  font-size: 32rpx;
  font-weight: bold;
  color: #333333;
  margin-bottom: 24rpx;
}

.comment-input-box {
  margin-bottom: 32rpx;
}

.reply-target-bar {
  margin-bottom: 12rpx;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12rpx;
}

.reply-target-text {
  font-size: 24rpx;
  color: #5f6d8b;
}

.reply-target-cancel {
  font-size: 24rpx;
  color: #d84b4b;
}

.comment-textarea {
  border: 1rpx solid #d9d9d9;
  border-radius: 12rpx;
  padding: 16rpx 20rpx;
  font-size: 28rpx;
  width: 100%;
  min-height: 120rpx;
  box-sizing: border-box;
  margin-bottom: 16rpx;
}

.comment-submit-btn {
  background-color: #1890ff;
  border-radius: 12rpx;
  padding: 16rpx 0;
  text-align: center;
}

.comment-submit-text {
  color: #ffffff;
  font-size: 28rpx;
}

.empty-comments {
  display: flex;
  justify-content: center;
  padding: 60rpx 0;
}

.comment-list {
  display: flex;
  flex-direction: column;
}

.comment-card {
  padding: 24rpx 0;
  border-bottom: 1rpx solid #f0f0f0;
}

.comment-card:last-child {
  border-bottom: none;
}

.comment-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12rpx;
}

.comment-avatar {
  width: 56rpx;
  height: 56rpx;
  border-radius: 50%;
  margin-right: 16rpx;
  background-color: #eeeeee;
}

.comment-avatar-fallback {
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba(24, 144, 255, 0.15);
}

.comment-avatar-text {
  font-size: 24rpx;
  font-weight: bold;
  color: #1890ff;
}

.comment-author-info {
  flex: 1;
  display: flex;
  flex-direction: column;
}

.comment-delete-btn {
  padding: 8rpx 12rpx;
}

.comment-delete-text {
  font-size: 22rpx;
  color: #d84b4b;
}

.comment-author-name {
  font-size: 26rpx;
  color: #333333;
  font-weight: 500;
}

.comment-date {
  font-size: 22rpx;
  color: #999999;
  margin-top: 2rpx;
}

.comment-content {
  font-size: 28rpx;
  color: #444444;
  line-height: 1.6;
  padding-left: 72rpx;
}

.comment-actions {
  margin-top: 10rpx;
  padding-left: 72rpx;
}

.comment-action-link {
  font-size: 24rpx;
  color: #4c6fd1;
}

.reply-list {
  margin-top: 16rpx;
  margin-left: 72rpx;
  padding: 18rpx;
  border-radius: 16rpx;
  background-color: #f7f9fc;
}

.reply-card + .reply-card {
  margin-top: 16rpx;
  padding-top: 16rpx;
  border-top: 1rpx solid #e9edf5;
}

.reply-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16rpx;
}

.reply-author {
  font-size: 24rpx;
  font-weight: 600;
  color: #3b455a;
}

.reply-date {
  font-size: 22rpx;
  color: #99a3b5;
}

.reply-content {
  display: block;
  margin-top: 8rpx;
  font-size: 26rpx;
  line-height: 1.6;
  color: #444444;
}

.reply-actions {
  margin-top: 10rpx;
  display: flex;
  gap: 24rpx;
}

.pagination {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 24rpx 0;
  gap: 24rpx;
}

.page-btn {
  background-color: #f5f5f5;
  border: 1rpx solid #d9d9d9;
  border-radius: 8rpx;
  padding: 12rpx 28rpx;
}

.page-btn--disabled {
  opacity: 0.4;
}

.page-btn-text {
  font-size: 26rpx;
  color: #333333;
}

.page-info {
  font-size: 26rpx;
  color: #666666;
}

.modal-mask {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 999;
}

.modal-content {
  width: 640rpx;
  background-color: #ffffff;
  border-radius: 20rpx;
  padding: 40rpx;
  max-height: 80vh;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}

.modal-title {
  font-size: 34rpx;
  font-weight: bold;
  color: #333333;
  text-align: center;
  margin-bottom: 32rpx;
}

.form-item {
  margin-bottom: 24rpx;
}

.form-item--switch {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.form-label {
  font-size: 28rpx;
  color: #333333;
  margin-bottom: 12rpx;
  display: block;
}

.form-input,
.form-picker,
.form-textarea {
  width: 100%;
  background-color: #f8f8f8;
  border-radius: 12rpx;
  padding: 20rpx 24rpx;
  font-size: 28rpx;
  box-sizing: border-box;
}

.form-textarea {
  min-height: 220rpx;
}

.form-picker-text {
  color: #333333;
}

.placeholder-text {
  color: #999999;
}

.modal-actions {
  display: flex;
  gap: 20rpx;
  margin-top: 32rpx;
}

.modal-btn {
  flex: 1;
  height: 84rpx;
  border-radius: 42rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}

.modal-btn--cancel {
  background-color: #f5f5f5;
}

.modal-btn--confirm {
  background-color: #1890ff;
}

.modal-btn-text {
  font-size: 28rpx;
  color: #666666;
}

.modal-btn-text--white {
  color: #ffffff;
}
</style>
