// frontend/src/pages/Community/index.tsx
import { useEffect, useState } from 'react'
import {
  Avatar,
  Button,
  Card,
  Empty,
  Form,
  Input,
  List,
  Modal,
  Select,
  Space,
  Spin,
  Switch,
  Tag,
  Typography,
  message,
} from 'antd'
import {
  EyeOutlined,
  LikeFilled,
  LikeOutlined,
  MessageOutlined,
  PlusOutlined,
  UserOutlined,
} from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { communityApi, CommunityPost } from '@/api/community'
import { categoryApi, type Category } from '@/api/modules'
import { useAppStore } from '@/stores/appStore'

const { Paragraph, Text, Title } = Typography
const { Search } = Input

const sortOptions = [
  { label: '最新', value: 'latest' as const },
  { label: '最热', value: 'hot' as const },
  { label: '最多赞', value: 'popular' as const },
]

const getUserIdFromToken = () => {
  const token = localStorage.getItem('token')
  if (!token) return ''

  try {
    const payload = JSON.parse(window.atob(token.split('.')[1] || ''))
    return payload?.userId ? String(payload.userId) : ''
  } catch {
    return ''
  }
}

export function Community() {
  const navigate = useNavigate()
  const user = useAppStore((state) => state.user)
  const [posts, setPosts] = useState<CommunityPost[]>([])
  const [loading, setLoading] = useState(false)
  const [total, setTotal] = useState(0)
  const [categories, setCategories] = useState<Array<Pick<Category, 'id' | 'name'>>>([])
  const [page, setPage] = useState(1)
  const [category, setCategory] = useState('')
  const [sort, setSort] = useState<'latest' | 'hot' | 'popular'>('latest')
  const [keyword, setKeyword] = useState('')
  const [showPostModal, setShowPostModal] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [editingPost, setEditingPost] = useState<CommunityPost | null>(null)
  const [form] = Form.useForm()

  const currentUserId = user?.id ? String(user.id) : getUserIdFromToken()
  const isEditing = !!editingPost
  const categoryOptions = [
    { label: '全部', value: '' },
    ...categories.map((item) => ({ label: item.name, value: String(item.id) })),
  ]
  const postCategoryOptions = [
    { label: '不分类', value: '' },
    ...categories.map((item) => ({ label: item.name, value: String(item.id) })),
  ]

  useEffect(() => {
    fetchCategories()
  }, [])

  useEffect(() => {
    fetchPosts()
  }, [page, category, sort])

  const fetchCategories = async () => {
    try {
      const result = await categoryApi.getAll()
      setCategories((result || []).map((item) => ({ id: item.id, name: item.name })))
    } catch (_error) {
      setCategories([])
    }
  }

  const fetchPosts = async (options?: { page?: number; keyword?: string }) => {
    setLoading(true)
    try {
      const result = await communityApi.getPosts({
        page: options?.page ?? page,
        pageSize: 10,
        sort,
        category: category || undefined,
        keyword: (options?.keyword ?? keyword) || undefined,
      })
      const data = result as unknown as { list: CommunityPost[]; pagination: { total: number } }
      setPosts(data.list || [])
      setTotal(data.pagination?.total || 0)
    } catch (_error) {
      console.error('获取帖子失败:', _error)
    } finally {
      setLoading(false)
    }
  }

  const ensureLogin = () => {
    const token = localStorage.getItem('token')
    if (!token) {
      message.warning('请先登录')
      navigate('/login')
      return false
    }
    return true
  }

  const resetPostForm = () => {
    form.resetFields()
    form.setFieldsValue({ isAnonymous: false, categoryId: '' })
    setEditingPost(null)
  }

  const handleCloseModal = () => {
    setShowPostModal(false)
    resetPostForm()
  }

  const handleSearch = (value: string) => {
    setKeyword(value)
    setPage(1)
    fetchPosts({ page: 1, keyword: value })
  }

  const handleLike = async (postId: number, isLiked: boolean) => {
    if (!ensureLogin()) return

    try {
      if (isLiked) {
        await communityApi.unlikePost(postId)
      } else {
        await communityApi.likePost(postId)
      }

      setPosts((prev) =>
        prev.map((item) =>
          item.id === postId
            ? { ...item, isLiked: !isLiked, likeCount: item.likeCount + (isLiked ? -1 : 1) }
            : item
        )
      )
    } catch (_error) {
      message.error('操作失败')
    }
  }

  const handleOpenCreate = () => {
    if (!ensureLogin()) return
    resetPostForm()
    setShowPostModal(true)
  }

  const handleOpenEdit = (post: CommunityPost) => {
    if (!ensureLogin()) return
    setEditingPost(post)
    form.setFieldsValue({
      title: post.title,
      content: post.content,
      isAnonymous: post.isAnonymous,
      categoryId: post.categoryId || '',
    })
    setShowPostModal(true)
  }

  const handleSubmitPost = async (values: {
    title: string
    content: string
    isAnonymous?: boolean
    categoryId?: string
  }) => {
    setSubmitting(true)
    try {
      if (editingPost) {
        await communityApi.updatePost(editingPost.id, {
          title: values.title.trim(),
          content: values.content.trim(),
          categoryId: values.categoryId || undefined,
          isAnonymous: Boolean(values.isAnonymous),
        })
        message.success('帖子已更新')
      } else {
        await communityApi.createPost({
          title: values.title.trim(),
          content: values.content.trim(),
          categoryId: values.categoryId || undefined,
          isAnonymous: Boolean(values.isAnonymous),
        })
        message.success('发帖成功')
      }

      handleCloseModal()
      setPage(1)
      fetchPosts({ page: 1 })
    } catch (_error) {
      message.error(editingPost ? '更新失败' : '发帖失败')
    } finally {
      setSubmitting(false)
    }
  }

  const handleDeletePost = (post: CommunityPost) => {
    Modal.confirm({
      title: '删除帖子',
      content: '删除后不可恢复，确认继续吗？',
      okText: '删除',
      cancelText: '取消',
      okButtonProps: { danger: true },
      onOk: async () => {
        try {
          await communityApi.deletePost(post.id)
          message.success('删除成功')

          const nextPage = posts.length === 1 && page > 1 ? page - 1 : page
          if (nextPage !== page) {
            setPage(nextPage)
          }
          fetchPosts({ page: nextPage })
        } catch (_error) {
          message.error('删除失败')
        }
      },
    })
  }

  const isOwnPost = (post: CommunityPost) => !!currentUserId && String(post.authorId) === currentUserId

  return (
    <div>
      <Card style={{ marginBottom: 16 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <Title level={3} style={{ margin: 0 }}>
            社区交流
          </Title>
          <Button type="primary" icon={<PlusOutlined />} onClick={handleOpenCreate}>
            发帖
          </Button>
        </div>

        <Search
          placeholder="搜索帖子..."
          allowClear
          onSearch={handleSearch}
          style={{ marginBottom: 16 }}
        />

        <Space>
          <Select
            value={category}
            onChange={(value) => {
              setCategory(value)
              setPage(1)
            }}
            options={categoryOptions}
            style={{ width: 120 }}
          />
          <Select
            value={sort}
            onChange={(value) => {
              setSort(value)
              setPage(1)
            }}
            options={sortOptions}
            style={{ width: 100 }}
          />
        </Space>
      </Card>

      <Spin spinning={loading}>
        {posts.length > 0 ? (
          <List
            dataSource={posts}
            renderItem={(post) => (
              <Card
                hoverable
                style={{ marginBottom: 12 }}
                onClick={() => navigate(`/community/${post.id}`)}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, marginBottom: 8 }}>
                  <div style={{ display: 'flex', alignItems: 'center', minWidth: 0 }}>
                    <Avatar size="small" icon={<UserOutlined />} src={post.author?.avatar} />
                    <div style={{ marginLeft: 8, minWidth: 0 }}>
                      <Text>
                        {post.isAnonymous ? '匿名用户' : post.author?.nickname || post.author?.username || '用户'}
                      </Text>
                      <div>
                        <Text type="secondary" style={{ fontSize: 12 }}>
                          {new Date(post.createdAt).toLocaleString()}
                        </Text>
                      </div>
                    </div>
                  </div>
                  {isOwnPost(post) && (
                    <Space size={4}>
                      <Button
                        type="link"
                        size="small"
                        onClick={(event) => {
                          event.stopPropagation()
                          handleOpenEdit(post)
                        }}
                      >
                        编辑
                      </Button>
                      <Button
                        type="link"
                        size="small"
                        danger
                        onClick={(event) => {
                          event.stopPropagation()
                          handleDeletePost(post)
                        }}
                      >
                        删除
                      </Button>
                    </Space>
                  )}
                </div>

                <Title level={5} style={{ marginBottom: 8 }}>
                  {post.isPinned && <Tag color="red">置顶</Tag>}
                  {post.title}
                </Title>

                <Paragraph ellipsis={{ rows: 2 }} style={{ color: '#666', marginBottom: 12 }}>
                  {post.content}
                </Paragraph>

                <Space size="large" wrap>
                  <span
                    onClick={(event) => {
                      event.stopPropagation()
                      handleLike(post.id, !!post.isLiked)
                    }}
                    style={{ cursor: 'pointer' }}
                  >
                    {post.isLiked ? <LikeFilled style={{ color: '#1890ff' }} /> : <LikeOutlined />}{' '}
                    {post.likeCount}
                  </span>
                  <span>
                    <MessageOutlined /> {post.commentCount}
                  </span>
                  <span>
                    <EyeOutlined /> {post.viewCount}
                  </span>
                  {(post.categoryName || post.category) && <Tag>{post.categoryName || post.category}</Tag>}
                  {post.isAnonymous && <Tag color="gold">匿名</Tag>}
                </Space>
              </Card>
            )}
            pagination={{
              current: page,
              total,
              pageSize: 10,
              onChange: setPage,
              showTotal: (value) => `共 ${value} 条`,
            }}
          />
        ) : (
          <Empty description="暂无帖子" />
        )}
      </Spin>

      <Modal
        title={isEditing ? '编辑帖子' : '发布帖子'}
        open={showPostModal}
        onCancel={handleCloseModal}
        footer={null}
        destroyOnClose
      >
        <Form
          form={form}
          layout="vertical"
          onFinish={handleSubmitPost}
          initialValues={{ isAnonymous: false, categoryId: '' }}
        >
          <Form.Item name="title" label="标题" rules={[{ required: true, message: '请输入标题' }]}>
            <Input placeholder="请输入帖子标题" maxLength={100} />
          </Form.Item>
          <Form.Item name="categoryId" label="分类">
            <Select options={postCategoryOptions} />
          </Form.Item>
          <Form.Item name="content" label="内容" rules={[{ required: true, message: '请输入内容' }]}>
            <Input.TextArea rows={6} placeholder="分享您的经验..." maxLength={5000} showCount />
          </Form.Item>
          <Form.Item name="isAnonymous" label="匿名发布" valuePropName="checked">
            <Switch />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" block loading={submitting}>
              {isEditing ? '保存修改' : '立即发布'}
            </Button>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

// mini-program/src/pages/community/index.vue
<template>
  <view class="community-page">
    <view class="header">
      <text class="header-title">社区交流</text>
      <view class="header-btn" @tap="onCreatePost">
        <text class="header-btn-text">+ 发帖</text>
      </view>
    </view>

    <view class="search-bar">
      <input
        v-model="keyword"
        class="search-input"
        placeholder="搜索帖子..."
        confirm-type="search"
        @confirm="onSearch"
      />
    </view>

    <view class="filter-row">
      <picker :range="filterCategoryOptions" range-key="name" :value="selectedFilterCategoryIndex" @change="onFilterCategoryChange">
        <view class="filter-picker">
          <text class="filter-text">{{ selectedFilterCategoryLabel }}</text>
          <text class="filter-arrow">▼</text>
        </view>
      </picker>
      <picker :range="sortOptions" range-key="label" :value="sortIndex" @change="onSortChange">
        <view class="filter-picker">
          <text class="filter-text">{{ sortOptions[sortIndex].label }}</text>
          <text class="filter-arrow">▼</text>
        </view>
      </picker>
    </view>

    <view v-if="loading && posts.length === 0" class="loading-box">
      <text class="loading-text">加载中...</text>
    </view>

    <view v-else-if="posts.length === 0" class="empty-box">
      <text class="empty-text">暂无帖子</text>
    </view>

    <view v-else class="post-list">
      <view
        v-for="post in posts"
        :key="post.id"
        class="post-card"
        @tap="goToDetail(post.id)"
      >
        <view class="post-author-row">
          <view class="post-author-main">
            <view class="avatar avatar-fallback">
              <text class="avatar-text">{{ post.isAnonymous ? '匿' : ((post.author?.nickname || post.author?.username || '用')[0]) }}</text>
            </view>
            <view class="author-info">
              <text class="author-name">
                {{ post.isAnonymous ? '匿名用户' : (post.author?.nickname || post.author?.username || '用户') }}
              </text>
              <text class="post-date">{{ formatDate(post.createdAt) }}</text>
            </view>
          </view>
          <view v-if="canManagePost(post)" class="post-manage-actions">
            <text class="post-manage-link" @tap.stop="onEditPost(post)">编辑</text>
            <text class="post-manage-link post-manage-link--danger" @tap.stop="onDeletePost(post.id)">删除</text>
          </view>
        </view>

        <view class="post-title-row">
          <view v-if="post.isPinned" class="pin-tag">
            <text class="pin-tag-text">置顶</text>
          </view>
          <text class="post-title">{{ post.title }}</text>
        </view>

        <text class="post-preview">{{ post.content }}</text>

        <view class="post-footer">
          <view class="post-meta">
            <view v-if="post.categoryName || post.category" class="category-tag">
              <text class="category-tag-text">{{ post.categoryName || post.category }}</text>
            </view>
            <view v-if="post.isAnonymous" class="anonymous-tag">
              <text class="anonymous-tag-text">匿名</text>
            </view>
          </view>
          <view class="post-stats">
            <view class="stat-item" @tap.stop="onToggleLike(post)">
              <text class="stat-icon" :class="{ 'stat-icon--liked': post.isLiked }">♥</text>
              <text class="stat-num">{{ post.likeCount || 0 }}</text>
            </view>
            <view class="stat-item">
              <text class="stat-icon">💬</text>
              <text class="stat-num">{{ post.commentCount || 0 }}</text>
            </view>
            <view class="stat-item">
              <text class="stat-icon">👁</text>
              <text class="stat-num">{{ post.viewCount || 0 }}</text>
            </view>
          </view>
        </view>
      </view>

      <view v-if="pagination.totalPages > 1" class="pagination">
        <view
          class="page-btn"
          :class="{ 'page-btn--disabled': pagination.page <= 1 }"
          @tap="changePage(pagination.page - 1)"
        >
          <text class="page-btn-text">上一页</text>
        </view>
        <text class="page-info">{{ pagination.page }} / {{ pagination.totalPages }}</text>
        <view
          class="page-btn"
          :class="{ 'page-btn--disabled': pagination.page >= pagination.totalPages }"
          @tap="changePage(pagination.page + 1)"
        >
          <text class="page-btn-text">下一页</text>
        </view>
      </view>
    </view>

    <view v-if="showPostModal" class="modal-mask" @tap.self="closePostModal">
      <view class="modal-content">
        <text class="modal-title">{{ modalTitle }}</text>

        <view class="form-item">
          <text class="form-label">标题</text>
          <input
            v-model="postForm.title"
            class="form-input"
            placeholder="请输入标题"
          />
        </view>

        <view class="form-item">
          <text class="form-label">分类</text>
          <picker :range="categoryOptions" range-key="name" :value="selectedCategoryIndex" @change="onCategoryChange">
            <view class="form-picker">
              <text :class="postForm.categoryId ? 'form-picker-text' : 'placeholder-text'">
                {{ selectedCategoryLabel }}
              </text>
            </view>
          </picker>
        </view>

        <view class="form-item">
          <text class="form-label">内容</text>
          <textarea
            v-model="postForm.content"
            class="form-textarea"
            placeholder="分享你的经验和想法..."
          />
        </view>

        <view class="form-item form-item--switch">
          <text class="form-label">匿名发布</text>
          <switch :checked="postForm.isAnonymous" color="#2ea97d" @change="onAnonymousChange" />
        </view>

        <view class="modal-actions">
          <view class="modal-btn modal-btn--cancel" @tap="closePostModal">
            <text class="modal-btn-text">取消</text>
          </view>
          <view class="modal-btn modal-btn--confirm" @tap="submitPost">
            <text class="modal-btn-text modal-btn-text--white">{{ submitButtonText }}</text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { communityApi } from '@/api/community'
import type { CommunityPost } from '@/api/community'
import { categoryApi, type Category } from '@/api/modules'
import dayjs from 'dayjs'

const sortOptions = [
  { label: '最新', value: 'latest' },
  { label: '最热', value: 'hot' },
  { label: '最多赞', value: 'popular' },
]

const keyword = ref('')
const sortIndex = ref(0)
const loading = ref(false)
const posts = ref<CommunityPost[]>([])
const categories = ref<Array<Pick<Category, 'id' | 'name'>>>([])
const pagination = reactive({ page: 1, pageSize: 10, total: 0, totalPages: 0 })
const showPostModal = ref(false)
const editingPostId = ref<number | null>(null)
const currentUserId = ref('')
const filterCategoryId = ref('')
const postForm = reactive({ title: '', content: '', categoryId: '', isAnonymous: false })

const categoryOptions = computed(() => [{ id: '', name: '不分类' }, ...categories.value])
const filterCategoryOptions = computed(() => [{ id: '', name: '全部分类' }, ...categories.value])
const selectedCategoryIndex = computed(() => {
  const index = categoryOptions.value.findIndex((item) => String(item.id) === postForm.categoryId)
  return index >= 0 ? index : 0
})
const selectedCategoryLabel = computed(() => {
  return categoryOptions.value[selectedCategoryIndex.value]?.name || '不分类'
})
const selectedFilterCategoryIndex = computed(() => {
  const index = filterCategoryOptions.value.findIndex((item) => String(item.id) === filterCategoryId.value)
  return index >= 0 ? index : 0
})
const selectedFilterCategoryLabel = computed(() => {
  return filterCategoryOptions.value[selectedFilterCategoryIndex.value]?.name || '全部分类'
})
const isEditing = computed(() => editingPostId.value !== null)
const modalTitle = computed(() => (isEditing.value ? '编辑帖子' : '发布帖子'))
const submitButtonText = computed(() => (isEditing.value ? '保存修改' : '发布'))

const formatDate = (date: string) => dayjs(date).format('YYYY-MM-DD HH:mm')

const syncCurrentUserId = () => {
  const storedUser = uni.getStorageSync('user') as { id?: string | number } | undefined
  currentUserId.value = storedUser?.id ? String(storedUser.id) : ''
}

const resetPostForm = () => {
  editingPostId.value = null
  postForm.title = ''
  postForm.content = ''
  postForm.categoryId = ''
  postForm.isAnonymous = false
}

const closePostModal = () => {
  showPostModal.value = false
  resetPostForm()
}

const fetchCategories = async () => {
  try {
    const res = await categoryApi.getAll()
    categories.value = (res || []).map((item) => ({ id: item.id, name: item.name }))
  } catch (_err) {
    categories.value = []
  }
}

const fetchPosts = async (options?: { page?: number; keyword?: string }) => {
  loading.value = true
  try {
    const params: Record<string, unknown> = {
      page: options?.page ?? pagination.page,
      pageSize: pagination.pageSize,
      sort: sortOptions[sortIndex.value].value,
    }
    if (filterCategoryId.value) {
      params.category = filterCategoryId.value
    }
    const nextKeyword = options?.keyword ?? keyword.value.trim()
    if (nextKeyword) {
      params.keyword = nextKeyword
    }

    const res = await communityApi.getPosts(params as any) as any
    posts.value = res.list || []
    if (res.pagination) {
      pagination.page = res.pagination.page
      pagination.total = res.pagination.total
      pagination.totalPages = res.pagination.totalPages
    }
  } catch (_err) {
    uni.showToast({ title: '加载失败', icon: 'none' })
  } finally {
    loading.value = false
  }
}

const onSearch = () => {
  pagination.page = 1
  fetchPosts({ page: 1 })
}

const onSortChange = (e: { detail: { value: number | string } }) => {
  sortIndex.value = Number(e.detail.value)
  pagination.page = 1
  fetchPosts({ page: 1 })
}

const onFilterCategoryChange = (e: { detail: { value: number | string } }) => {
  const target = filterCategoryOptions.value[Number(e.detail.value)]
  filterCategoryId.value = target ? String(target.id || '') : ''
  pagination.page = 1
  fetchPosts({ page: 1 })
}

const changePage = (page: number) => {
  if (page < 1 || page > pagination.totalPages) return
  pagination.page = page
  fetchPosts()
}

const goToDetail = (id: number) => {
  uni.navigateTo({ url: `/pages/post-detail/index?id=${id}` })
}

const onToggleLike = async (post: CommunityPost) => {
  if (!checkLogin()) return
  try {
    if (post.isLiked) {
      await communityApi.unlikePost(post.id)
      post.isLiked = false
      post.likeCount--
    } else {
      await communityApi.likePost(post.id)
      post.isLiked = true
      post.likeCount++
    }
  } catch (_err) {
    uni.showToast({ title: '操作失败', icon: 'none' })
  }
}

const checkLogin = (): boolean => {
  const token = uni.getStorageSync('token')
  if (!token) {
    uni.navigateTo({ url: '/pages/login/index' })
    return false
  }
  return true
}

const canManagePost = (post: CommunityPost) => {
  return !!currentUserId.value && String(post.authorId) === currentUserId.value
}

const onCreatePost = () => {
  if (!checkLogin()) return
  resetPostForm()
  showPostModal.value = true
}

const onEditPost = (post: CommunityPost) => {
  if (!checkLogin()) return
  editingPostId.value = post.id
  postForm.title = post.title
  postForm.content = post.content
  postForm.categoryId = post.categoryId || ''
  postForm.isAnonymous = Boolean(post.isAnonymous)
  showPostModal.value = true
}

const onDeletePost = (postId: number) => {
  uni.showModal({
    title: '删除帖子',
    content: '删除后不可恢复，确认继续吗？',
    success: async (res) => {
      if (!res.confirm) return
      try {
        await communityApi.deletePost(postId)
        uni.showToast({ title: '删除成功', icon: 'success' })
        if (posts.value.length === 1 && pagination.page > 1) {
          pagination.page -= 1
        }
        fetchPosts()
      } catch (_err) {
        uni.showToast({ title: '删除失败', icon: 'none' })
      }
    },
  })
}

const onCategoryChange = (e: { detail: { value: number | string } }) => {
  const target = categoryOptions.value[Number(e.detail.value)]
  postForm.categoryId = target ? String(target.id || '') : ''
}

const onAnonymousChange = (e: any) => {
  postForm.isAnonymous = Boolean(e?.detail?.value)
}

const submitPost = async () => {
  if (!postForm.title.trim()) {
    uni.showToast({ title: '请输入标题', icon: 'none' })
    return
  }
  if (!postForm.content.trim()) {
    uni.showToast({ title: '请输入内容', icon: 'none' })
    return
  }

  try {
    if (editingPostId.value !== null) {
      await communityApi.updatePost(editingPostId.value, {
        title: postForm.title.trim(),
        content: postForm.content.trim(),
        categoryId: postForm.categoryId || undefined,
        isAnonymous: postForm.isAnonymous,
      })
      uni.showToast({ title: '更新成功', icon: 'success' })
    } else {
      await communityApi.createPost({
        title: postForm.title.trim(),
        content: postForm.content.trim(),
        categoryId: postForm.categoryId || undefined,
        isAnonymous: postForm.isAnonymous,
      })
      uni.showToast({ title: '发布成功', icon: 'success' })
    }

    closePostModal()
    pagination.page = 1
    fetchPosts({ page: 1 })
  } catch (_err) {
    uni.showToast({ title: editingPostId.value !== null ? '更新失败' : '发布失败', icon: 'none' })
  }
}

onMounted(() => {
  syncCurrentUserId()
  fetchCategories()
  fetchPosts()
})

onShow(() => {
  syncCurrentUserId()
  fetchPosts()
})
</script>

<style scoped>
.community-page {
  min-height: 100vh;
  background-color: #f5f5f5;
  padding-bottom: 40rpx;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 24rpx 32rpx;
  background-color: #ffffff;
}

.header-title {
  font-size: 36rpx;
  font-weight: bold;
  color: #333333;
}

.header-btn {
  background-color: #1890ff;
  border-radius: 32rpx;
  padding: 12rpx 28rpx;
}

.header-btn-text {
  color: #ffffff;
  font-size: 26rpx;
}

.search-bar {
  padding: 16rpx 32rpx;
  background-color: #ffffff;
}

.search-input {
  background-color: #f5f5f5;
  border-radius: 32rpx;
  padding: 16rpx 28rpx;
  font-size: 28rpx;
}

.filter-row {
  display: flex;
  gap: 20rpx;
  padding: 16rpx 32rpx;
  background-color: #ffffff;
  border-bottom: 1rpx solid #f0f0f0;
}

.filter-picker {
  display: flex;
  align-items: center;
  background-color: #f5f5f5;
  border-radius: 24rpx;
  padding: 10rpx 24rpx;
  gap: 8rpx;
}

.filter-text {
  font-size: 26rpx;
  color: #333333;
}

.filter-arrow {
  font-size: 20rpx;
  color: #999999;
}

.loading-box,
.empty-box {
  display: flex;
  justify-content: center;
  padding: 100rpx 0;
}

.loading-text,
.empty-text {
  font-size: 28rpx;
  color: #999999;
}

.post-list {
  padding: 16rpx 32rpx;
}

.post-card {
  background-color: #ffffff;
  border-radius: 16rpx;
  padding: 28rpx;
  margin-bottom: 20rpx;
  box-shadow: 0 2rpx 12rpx rgba(0, 0, 0, 0.05);
}

.post-author-row {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 16rpx;
  margin-bottom: 16rpx;
}

.post-author-main {
  display: flex;
  align-items: center;
  min-width: 0;
}

.post-manage-actions {
  display: flex;
  align-items: center;
  gap: 20rpx;
  flex-shrink: 0;
}

.post-manage-link {
  font-size: 24rpx;
  color: #1890ff;
}

.post-manage-link--danger {
  color: #ff4d4f;
}

.avatar {
  width: 64rpx;
  height: 64rpx;
  border-radius: 50%;
  margin-right: 16rpx;
  background-color: #eeeeee;
}

.avatar-fallback {
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba(24, 144, 255, 0.15);
}

.avatar-text {
  font-size: 26rpx;
  font-weight: bold;
  color: #1890ff;
}

.author-info {
  display: flex;
  flex-direction: column;
  min-width: 0;
}

.author-name {
  font-size: 26rpx;
  color: #333333;
  font-weight: 500;
}

.post-date {
  font-size: 22rpx;
  color: #999999;
  margin-top: 4rpx;
}

.post-title-row {
  display: flex;
  align-items: center;
  gap: 10rpx;
  margin-bottom: 12rpx;
}

.pin-tag {
  background-color: #ff4d4f;
  border-radius: 6rpx;
  padding: 2rpx 10rpx;
  flex-shrink: 0;
}

.pin-tag-text {
  font-size: 20rpx;
  color: #ffffff;
}

.post-title {
  font-size: 30rpx;
  font-weight: bold;
  color: #333333;
}

.post-preview {
  font-size: 26rpx;
  color: #666666;
  line-height: 1.6;
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  margin-bottom: 16rpx;
}

.post-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 20rpx;
}

.post-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 12rpx;
}

.category-tag,
.anonymous-tag {
  border-radius: 6rpx;
  padding: 4rpx 14rpx;
}

.category-tag {
  background-color: #e6f7ff;
}

.category-tag-text {
  font-size: 22rpx;
  color: #1890ff;
}

.anonymous-tag {
  background-color: #fff7e6;
}

.anonymous-tag-text {
  font-size: 22rpx;
  color: #d48806;
}

.post-stats {
  display: flex;
  gap: 24rpx;
  flex-shrink: 0;
}

.stat-item {
  display: flex;
  align-items: center;
  gap: 6rpx;
}

.stat-icon {
  font-size: 24rpx;
}

.stat-icon--liked {
  color: #ff4d4f;
}

.stat-num {
  font-size: 22rpx;
  color: #999999;
}

.pagination {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 24rpx 0;
  gap: 24rpx;
}

.page-btn {
  background-color: #ffffff;
  border: 1rpx solid #d9d9d9;
  border-radius: 8rpx;
  padding: 12rpx 28rpx;
}

.page-btn--disabled {
  opacity: 0.4;
}

.page-btn-text {
  font-size: 26rpx;
  color: #333333;
}

.page-info {
  font-size: 26rpx;
  color: #666666;
}

.modal-mask {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 999;
}

.modal-content {
  width: 640rpx;
  background-color: #ffffff;
  border-radius: 20rpx;
  padding: 40rpx;
  max-height: 80vh;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}

.modal-title {
  font-size: 34rpx;
  font-weight: bold;
  color: #333333;
  text-align: center;
  margin-bottom: 32rpx;
}

.form-item {
  margin-bottom: 24rpx;
}

.form-item--switch {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.form-label {
  font-size: 28rpx;
  color: #333333;
  margin-bottom: 12rpx;
  display: block;
}

.form-input,
.form-picker,
.form-textarea {
  width: 100%;
  background-color: #f8f8f8;
  border-radius: 12rpx;
  padding: 20rpx 24rpx;
  font-size: 28rpx;
  box-sizing: border-box;
}

.form-textarea {
  min-height: 220rpx;
}

.form-picker-text {
  color: #333333;
}

.placeholder-text {
  color: #999999;
}

.modal-actions {
  display: flex;
  gap: 20rpx;
  margin-top: 32rpx;
}

.modal-btn {
  flex: 1;
  height: 84rpx;
  border-radius: 42rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}

.modal-btn--cancel {
  background-color: #f5f5f5;
}

.modal-btn--confirm {
  background-color: #1890ff;
}

.modal-btn-text {
  font-size: 28rpx;
  color: #666666;
}

.modal-btn-text--white {
  color: #ffffff;
}
</style>
